### PR TITLE
Fixed the crash in get_source.

### PR DESCRIPTION
**Pull request by stuartbrussell-intuit**
AfMSessionController.m
(init)
- Restored setting Finder as the currentApplication.

(allWindows)
- Restored the currentApplication as the first item in the returned array.

(xmlPageSourceFromRootUIElement:pathMap:xPath:)
- Restored using currentApplication as the default rootElement.

(xmlPageSourceHelperFromRootUIElement:rootXMLElement:path:pathMap:xPath:)
- Fixed the crash by removing an optimization.

development.py
- Re-added. Got tired of stashing and unstashing. This is not a demo or example, it's a scratchpad.

### CODE REVIEW

**Comment by penguinho** [comment]
@jlipps, I think this is all we were missing to possibly integrate with appium desktop. If you download the 0.3.0 release it should be compatible

**Comment by jlipps** [comment]
get_source works great now! unfortunately the screenshot command doesn't appear to be sending back valid base64 encoded png strings.

in general i wonder if some of the response objects are wrong coming from the mac server, it almost looks like they're quoted rather than plain json strings.

**Comment by stuartbrussell-intuit** [comment]
I'm looking into the screenshot command.

**Comment by penguinho** [comment]
I'll see if I can take a look at this in the next few days. Should be a simple fix.

**Comment by penguinho** [comment]
As bad as it sounds, I'm thinking this may be the way to go.

http://stackoverflow.com/questions/25835621/how-do-i-simulate-the-screenshot-function-mac-cocoa

**Comment by jlipps** [comment]
@penguinho won't that just get a screencap of the entire desktop? we'd need one of just the app, and for all the locations returned in the xml to be relative to the app as well.

**Comment by mykola-mokhnach** [comment]
how about something like this?

```objc
int main(int argc, const char * argv[]) {
    @autoreleasepool {
        if (argc < 2) {
            return -1;
        }
        int simWindowPid = getWindowPid();
        if (simWindowPid <= 0 ) {
            return -1;
        }
        CGImageRef img = CGWindowListCreateImage(CGRectNull, kCGWindowListOptionIncludingWindow, simWindowPid, kCGWindowImageBoundsIgnoreFraming);
        size_t currentWidth = CGImageGetWidth(img);
        size_t currentHeight = CGImageGetHeight(img);
        // Remove the top window bar from the screenshot
        img = CGImageCreateWithImageInRect(img, CGRectMake(0, TOP_BAR_HEIGHT, currentWidth, currentHeight - TOP_BAR_HEIGHT));
        NSMutableData *imgData = [[NSMutableData alloc] init];
        CGImageDestinationRef imgDest = CGImageDestinationCreateWithData((__bridge CFMutableDataRef)imgData, kUTTypePNG, 1, NULL);
        CGImageDestinationAddImage(imgDest, img, NULL);
        BOOL finalizeRes = CGImageDestinationFinalize(imgDest);
        if(!finalizeRes) return -1;
        
       // return [imgData base64EncodedStringWithOptions:0];
    }
    return 0;
}

```

**Comment by stuartbrussell-intuit** [comment]
I’ve got code in there already that creates a screen shot., but it creates a file instead of returning it as a command response.

see [AfMSessionController screenCaptureToFile:] and [AfMSessionController screenCaptureToClipboard].

-Stuart

**Comment by stuartbrussell-intuit** [comment]
Wait, I just re-read Jonathan's comment about the current window.

**Comment by penguinho** [comment]
I'm not sure how we want to do this.

Since Appium for Mac is OS-wide automation, everything is relative from its position on the display for the OS; I don't believe the coordinates returned are specific to the window in which the UI elements are positioned. Because of this, I think it makes sense to use the entire desktop for the screenshot instead of the current window.

Correct me if I'm wrong, @stuartbrussell-intuit

**Comment by stuartbrussell-intuit** [comment]
OK there are two related issues. These are interesting because of the OS-wide nature of AfM as Dan pointed out.

1. What bounds of screen shot to take.  The current paradigm is screen-wide, and the code is done, except for what Jonathan pointed out for base64EncodedString. One thing to consider is that the "display" can have multiple monitors, so we may want to restrict it to the main monitor. A question presents itself: what is Microsoft doing about this? We could try to match policies.

2. Element locations. By default, PFAssistive.framework returns screen-relative, and AfM just passes that back to the caller. For example, the Dock, menu bar and Finder desktop icons are not really in a "window" per se. As with screen shot, let's check with Microsoft about this. They may also be wrestling with this paradigm shift.

**Comment by jlipps** [comment]
Yes, these are the issues. WinAppDriver currently returns partial-desktop screenshots, the same dimensions as the app window, but they are of the desktop (not the app); so if another app is on top of the AUT, you get a weird crop of the other app. They're working on fixing this. I believe their element locations are also desktop-relative, not app-relative. So this is a bad situation.

Whatever you pick (desktop or app), screenshot and element coordinates should be the same. Personally I'd argue that what the user typically expects is a screenshot of the AUT and for element positions to be relative to the AUT & screenshot. If you're pushing for a "desktop automation" modality where you want users to not think of apps but to think of the entire desktop, then OK. But this will be odd for the inspector as well (are you going to return all of the elements of all the apps of the desktop? And if not, why get a screenshot of it?)

You guys can decide what's possible and what's the right approach for this project, but I think this will only be valuable in the inspector under the conditions I described.

cc @yodurr

**Comment by stuartbrussell-intuit** [comment]
The PR is merged and this is morphing into another subject, so I'm moving the discussion to the new issue, https://github.com/appium/appium-for-mac/issues/21

**Pull request merged**
